---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc-windows
  namespace: windows
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-windows
  resources:
    requests:
      storage: 5Gi
